### ISSUE TITLE
blank tags with id3v2

### ISSUE THREAD

**Issue by tastytea** [AndrewRadev/id3.vim#8]
Using the file i attached in #7, i only get blank tags in neovim 0.8.0. The files that threw errors with `id3tool` don't throw errors anymore but they too only show blank tags.

```shellsession
% id3v2 --version
id3v2 0.1.12
Uses id3lib-3.8.3
``` 

![screenshot of blank tags in neovim](https://user-images.githubusercontent.com/3681516/208584363-4d094e23-972c-4f54-be1e-5b29b5f91e60.png)

**Comment by tastytea** [comment]
`id3v2 -l` reports “No ID3 tag” although `easytag`, `picard` and `file` say that it has ID3v2.4 tags. The ID3 version could be the problem, because the readme of id3lib says this:

> id3lib is a software library for manipulating ID3v1/v1.1 and ID3v2 tags.
> id3lib 3.0.x conforms to all ID3v2 standards up to and including the ID3v2.3.0
> informal standard.

**Comment by AndrewRadev** [comment]
I think we went through explanations for the `id3v2` and `id3tool` problems in other issues, and with `id3-json`, we have a solution, so I'll go ahead and close this. Please reopen (or open a new one) if you run into more issues.
