### ISSUE TITLE
Support `.opus` files

### ISSUE THREAD

**Issue by storopoli** [AndrewRadev/id3.vim#9]
I have migrated most of my `.mp3` to `.opus`. I am having a hard time editing stuff with https://github.com/fmang/opustags and bash scripts. Opus support would be great!

**Comment by AndrewRadev** [comment]
I've pushed some support using `opustags`, could you let me know if it works alright? Based on your description, I've set it up to activate for files with an `.opus` extension -- is there some other common one for this kind of file?

**Comment by storopoli** [comment]
Works like a charm! Thanks!
